apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: mynamespace
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-download-file
    image: busybox
    command:
    - sh
    - -c
    - 'wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/nginx-app.yaml'
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  containers:
  - name: myapp-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: mynamespace
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80    
    #refer readme for notes
 
